"""PDF report mock response handler."""

from __future__ import annotations

from collections.abc import AsyncGenerator

from .artifact_collector import ArtifactCollector
from .registry import registry


@registry.register(
    keywords=["report", "pdf"],
    priority=5,
    description="Generate a PDF report",
)
async def handle_report(
    message: str,
    context: dict,
) -> AsyncGenerator[dict, None]:
    """Generate PDF report response."""
    collector: ArtifactCollector = context["collector"]

    yield {"type": "text", "content": "## Generating PDF Report...\n"}

    pdf_content = {
        "title": "Daily P&L Report",
        "tables": [
            {
                "title": "P&L by Desk",
                "data": [
                    {"desk": "FX", "pnl": 125000},
                    {"desk": "Rates", "pnl": -45000},
                    {"desk": "Credit", "pnl": 83000},
                    {"desk": "Commodities", "pnl": 22000},
                ],
            },
            {
                "title": "Risk Summary",
                "data": [
                    {"metric": "VaR 95%", "value": "$2.5M"},
                    {"metric": "VaR 99%", "value": "$3.8M"},
                ],
            },
        ],
        "text": "Report generated by FinAgent",
    }
    collector.pdf(pdf_content, title="Daily Report")
    artifact = collector.artifacts[-1]
    yield {
        "type": "pdf",
        "id": artifact["id"],
        "title": "Daily Report",
        "data": artifact["data"],
    }
